# using Jekyll defaults: see https://jekyllrb.com/docs/configuration

# we'll need /rotaract until we change the redirection on current (prod) host
#destination: ./_site/rotaract
#baseurl:     /rotaract

include: ['_pages']
exclude: [README.md]
